[workspace]
members = [
    "crates/*",
]
default-members = [
    "crates/*"
]
resolver = "2"

[workspace.dependencies]
# Own crates
algorithm = { path = "crates/algorithm" }
ffi-c = { path = "crates/ffi-c" }